=== jwillia/kc-sql/src/main/xsd/hrmanifest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:element name="hrmanifest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="records">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="record" type="RecordType" maxOccurs="unbounded"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="submitterId" type="string40Type"
				use="required"></xs:attribute>
			<xs:attribute name="transactionId" type="string40Type"
				use="required"></xs:attribute>
			<xs:attribute name="reportDate" type="xs:dateTime" use="required"></xs:attribute>
			<xs:attribute name="recordCount" type="xs:int" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="RecordType">
		<xs:sequence>
			<xs:element name="affiliations">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="affiliation" type="AffiliationType"
							minOccurs="1" maxOccurs="1"></xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="addresses">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="address" type="AddressType"
							minOccurs="0" maxOccurs="unbounded"></xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="names">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="NameType" minOccurs="1"
							maxOccurs="unbounded"></xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="phones">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="phone" type="PhoneType" minOccurs="0"
							maxOccurs="unbounded"></xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="emails">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="email" type="EmailType" minOccurs="0"
							maxOccurs="unbounded"></xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="kcExtendedAttributes" type="KCExtendedAttributesType"
				maxOccurs="1" minOccurs="0"></xs:element>
			<xs:element name="degrees">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="degree" type="DegreeDataType"
							maxOccurs="1" minOccurs="0"></xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="appointments">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="appointment" type="AppointmentDataType"
							maxOccurs="1" minOccurs="0"></xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="principalId" type="string40Type" use="required"></xs:attribute>
		<xs:attribute name="principalName" type="string40Type"
			use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="AffiliationType">
		<xs:attribute name="affiliationType" type="string40Type"
			use="required"></xs:attribute>
		<xs:attribute name="campus" type="string2Type" use="required"></xs:attribute>
		<xs:attribute name="employeeStatus" type="string40Type"
			use="required"></xs:attribute>
		<xs:attribute name="employeeType" type="string40Type"
			use="required"></xs:attribute>
		<xs:attribute name="baseSalaryAmount" type="xs:float"
			use="required"></xs:attribute>
		<xs:attribute name="primaryDepartment" type="string40Type"
			use="required"></xs:attribute>
		<xs:attribute name="employeeId" type="string40Type" use="required"></xs:attribute>
		<xs:attribute name="primaryEmployment" type="xs:boolean"
			default="false"></xs:attribute>
		<xs:attribute name="active" type="xs:boolean" default="true"></xs:attribute>
		<xs:attribute name="default" type="xs:boolean" default="false"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="AddressType">
		<xs:attribute name="addressType" type="string40Type"></xs:attribute>
		<xs:attribute name="addressLine1" type="string45Type"></xs:attribute>
		<xs:attribute name="addressLine2" type="string45Type"></xs:attribute>
		<xs:attribute name="addressLine3" type="string45Type"></xs:attribute>
		<xs:attribute name="city" type="string30Type"></xs:attribute>
		<xs:attribute name="stateOrProvince" type="string2Type"></xs:attribute>
		<xs:attribute name="postalCode" type="string20Type"></xs:attribute>
		<xs:attribute name="country" type="string2Type"></xs:attribute>
		<xs:attribute name="default" type="xs:boolean" default="false"></xs:attribute>
		<xs:attribute name="active" type="xs:boolean" default="false"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="NameType">
		<xs:attribute name="nameCode" type="string40Type" use="required"></xs:attribute>
		<xs:attribute name="prefix" type="string20Type"></xs:attribute>
		<xs:attribute name="firstName" type="string40Type" use="required"></xs:attribute>
		<xs:attribute name="lastName" type="string80Type" use="required"></xs:attribute>
		<xs:attribute name="suffix" type="string20Type"></xs:attribute>
		<xs:attribute name="default" type="xs:boolean" default="false"></xs:attribute>
		<xs:attribute name="active" type="xs:boolean" default="false"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="PhoneType">
		<xs:attribute name="phoneType" type="string40Type"></xs:attribute>
		<xs:attribute name="phoneNumber" type="string20Type"></xs:attribute>
		<xs:attribute name="extension" type="string8Type"></xs:attribute>
		<xs:attribute name="country" type="string2Type"></xs:attribute>
		<xs:attribute name="default" type="xs:boolean" default="false"></xs:attribute>
		<xs:attribute name="active" type="xs:boolean" default="false"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="EmailType">
		<xs:attribute name="emailType" type="string40Type"></xs:attribute>
		<xs:attribute name="emailAddress" type="string200Type"></xs:attribute>
		<xs:attribute name="default" type="xs:boolean" default="false"></xs:attribute>
		<xs:attribute name="active" type="xs:boolean" default="false"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="KCExtendedAttributesType">
		<xs:attribute name="country" type="string30Type"></xs:attribute>
		<xs:attribute name="ageByFiscalYear" type="xs:int"></xs:attribute>
		<xs:attribute name="race" type="string30Type"></xs:attribute>
		<xs:attribute name="educationLevel" type="string30Type"></xs:attribute>
		<xs:attribute name="degree" type="string11Type"></xs:attribute>
		<xs:attribute name="major" type="string30Type"></xs:attribute>
		<xs:attribute name="handicapped" type="xs:boolean"></xs:attribute>
		<xs:attribute name="handicapType" type="string30Type"></xs:attribute>
		<xs:attribute name="veteran" type="xs:boolean"></xs:attribute>
		<xs:attribute name="veteranType" type="string30Type"></xs:attribute>
		<xs:attribute name="visa" type="xs:boolean"></xs:attribute>
		<xs:attribute name="visaType" type="string30Type"></xs:attribute>
		<xs:attribute name="visaCode" type="string20Type"></xs:attribute>
		<xs:attribute name="visaRenewalDate" type="xs:dateTime"></xs:attribute>
		<xs:attribute name="officeLocation" type="string30Type"></xs:attribute>
		<xs:attribute name="secondaryOfficeLocation" type="string30Type"></xs:attribute>
		<xs:attribute name="school" type="string50Type"></xs:attribute>
		<xs:attribute name="yearGraduated" type="string30Type"></xs:attribute>
		<xs:attribute name="directoryDepartment" type="string30Type"></xs:attribute>
		<xs:attribute name="vacationAccrual" type="xs:boolean"></xs:attribute>
		<xs:attribute name="onSabbatical" type="xs:boolean"></xs:attribute>
		<xs:attribute name="idProvided" type="string30Type"></xs:attribute>
		<xs:attribute name="idVerified" type="string30Type"></xs:attribute>
		<xs:attribute name="citizenshipType" type="xs:int"></xs:attribute>
		<xs:attribute name="multiCampusPrincipalId" type="string40Type"></xs:attribute>
		<xs:attribute name="multiCampusPrincipalName" type="string100Type"></xs:attribute>
		<xs:attribute name="salaryAnniversaryDate" type="xs:date"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="DegreeDataType">
		<xs:attribute name="degree" type="string80Type"></xs:attribute>
		<xs:attribute name="degreeType" type="string6Type"></xs:attribute>
		<xs:attribute name="graduationYear" type="string4Type"></xs:attribute>
		<xs:attribute name="fieldOfStudy" type="string80Type"></xs:attribute>
		<xs:attribute name="specialization" type="string80Type"></xs:attribute>
		<xs:attribute name="school" type="string50Type"></xs:attribute>
		<xs:attribute name="schoolId" type="string20Type"></xs:attribute>
		<xs:attribute name="schoolIdCode" type="string3Type"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="AppointmentDataType">
		<xs:attribute name="unit" type="string8Type"></xs:attribute>
		<xs:attribute name="jobCode" type="string6Type"></xs:attribute>
		<xs:attribute name="appointmentType" type="string3Type"></xs:attribute>
		<xs:attribute name="salary" type="xs:float"></xs:attribute>
		<xs:attribute name="startDate" type="xs:date"></xs:attribute>
		<xs:attribute name="endDate" type="xs:date"></xs:attribute>
		<xs:attribute name="jobTitle" type="string50Type"></xs:attribute>
		<xs:attribute name="preferedJobTitle" type="string50Type"></xs:attribute>
	</xs:complexType>

	<xs:simpleType name="string2Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="2"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string3Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="3"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string4Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="4"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string6Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="6"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string8Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="8"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string11Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="11"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string20Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="20"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string30Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="30"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string40Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="40"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string45Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="45"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string50Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string80Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="80"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="string100Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="string200Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="200"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== jwillia/kc-sql/src/test/resources/issue11.xml
<?xml version="1.0" encoding="UTF-8"?>
<hrmanifest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="https://github.com/rSmart/ce-tech-docs/tree/master/v1_0
                       https://raw.github.com/rSmart/ce-tech-docs/master/v1_0/hrmanifest.xsd"
                xmlns="https://github.com/rSmart/ce-tech-docs/tree/master/v1_0"
   schemaVersion="1.0"
   recordCount="3"
   statusEmailRecipient="foo@bar.com">
  <records>
    <!-- should produce an error for record 2 with principal name 'harriet' because
      "GOOBER" is not a valid affiliationType -->
    <record principalName="harriet">
      <affiliations>
        <affiliation affiliationType="GOOBER"
          campus="MN"
          default="true"
          active="true">
          <employment
            employeeStatus="A"
            employeeType="P"
            baseSalaryAmount="50180"
            primaryDepartment="MATH"
            employeeId="092001234"
            primaryEmployment="true" />
        </affiliation>
      </affiliations>
      <addresses>
        <address addressTypeCode="HM"
          addressLine1="1234 E. Main St."
          addressLine2="Apt. 8C"
          city="Minneapolis"
          stateOrProvince="MN"
          postalCode="34567"
          country="US"
          default="true"
          active="true" />
      </addresses>
      <names>
        <name nameCode="PRM"
          prefix="Mr"
          firstName="Jonathon"
          middleName="R"
          lastName="Doe"
          default="true"
          active="true" />
      </names>
      <phones>
        <phone phoneType="WRK"
          phoneNumber="204-391-1101"
          country="US"
          default="true"
          active="true" />
        <phone phoneType="HM"
          phoneNumber="204-718-3221"
          country="US"
          active="true" />
      </phones>
      <emails>
        <email emailType="WRK"
          emailAddress="jdoe@university.edu"
          default="true"
          active="true" />
      </emails>
      <kcExtendedAttributes county="Maricopa"
        ageByFiscalYear="52"
        race="CAUCASIAN"
        educationLevel="PHD"
        degree="PhD"
        major="MATHEMATICS"
        handicapped="true"
        handicapType="TODO:handicapType"
        veteran="true"
        veteranType="A"
        visa="true"
        visaCode="TODO:visaCode"
        visaType="TODO:visaType"
        visaRenewalDate="2013-12-25"
        officeLocation="503 Carter Hall"
        secondaryOfficeLocation="88 Regan Hall"
        school="MATH"
        yearGraduated="1983"
        directoryDepartment="MATH"
        directoryTitle="Master of the Universe"
        primaryTitle="Leader of the Evil Horde"
        vacationAccrual="true"
        idProvided="John_Doe"
        idVerified="John_Doe_Verified"
        multiCampusPrincipalId="0002"
        multiCampusPrincipalName="jdoe2"
        onSabbatical="true"
        citizenshipType="1"
        salaryAnniversaryDate="2010-01-01"/>
      <degrees>
        <degree degree="PhD"
          degreeCode="DD"
          graduationYear="1983"
          fieldOfStudy="Mathematics"
          specialization="non-linear algebra"
          school="Texas A&amp;M University"
          schoolId="1234"
          schoolIdCode="UMN" />
      </degrees>
      <appointments>
        <appointment unitNumber="IN-CARD"
          jobCode="0010"
          appointmentType="APP"
          salary="50180"
          startDate="2010-01-01"
          jobTitle="Professor"
          preferedJobTitle="Professor"/>
      </appointments>
    </record>
    <!-- should produce an error for record 2 with principal name 'harriet' because it is a duplicate ID -->
    <record principalName="harriet">
      <affiliations>
        <affiliation affiliationType="faculty"
          campus="MN"
          default="true"
          active="true">
          <employment
            employeeStatus="A"
            employeeType="P"
            baseSalaryAmount="50180"
            primaryDepartment="MATH"
            employeeId="092001234"
            primaryEmployment="true" />
        </affiliation>
      </affiliations>
      <addresses>
        <address addressTypeCode="HM"
          addressLine1="1234 E. Main St."
          addressLine2="Apt. 8C"
          city="Minneapolis"
          stateOrProvince="MN"
          postalCode="34567"
          country="US"
          default="true"
          active="true" />
      </addresses>
      <names>
        <name nameCode="PRM"
          prefix="Mr"
          firstName="Jonathon"
          middleName="R"
          lastName="Doe"
          default="true"
          active="true" />
      </names>
      <phones>
        <phone phoneType="WRK"
          phoneNumber="204-391-1101"
          country="US"
          default="true"
          active="true" />
        <phone phoneType="HM"
          phoneNumber="204-718-3221"
          country="US"
          active="true" />
      </phones>
      <emails>
        <email emailType="WRK"
          emailAddress="jdoe@university.edu"
          default="true"
          active="true" />
      </emails>
      <kcExtendedAttributes county="Maricopa"
        ageByFiscalYear="52"
        race="CAUCASIAN"
        educationLevel="PHD"
        degree="PhD"
        major="MATHEMATICS"
        handicapped="true"
        handicapType="TODO:handicapType"
        veteran="true"
        veteranType="A"
        visa="true"
        visaCode="TODO:visaCode"
        visaType="TODO:visaType"
        visaRenewalDate="2013-12-25"
        officeLocation="503 Carter Hall"
        secondaryOfficeLocation="88 Regan Hall"
        school="MATH"
        yearGraduated="1983"
        directoryDepartment="MATH"
        directoryTitle="Master of the Universe"
        primaryTitle="Leader of the Evil Horde"
        vacationAccrual="true"
        idProvided="John_Doe"
        idVerified="John_Doe_Verified"
        multiCampusPrincipalId="0002"
        multiCampusPrincipalName="jdoe2"
        onSabbatical="true"
        citizenshipType="1"
        salaryAnniversaryDate="2010-01-01"/>
      <degrees>
        <degree degree="PhD"
          degreeCode="DD"
          graduationYear="1983"
          fieldOfStudy="Mathematics"
          specialization="non-linear algebra"
          school="Texas A&amp;M University"
          schoolId="1234"
          schoolIdCode="UMN" />
      </degrees>
      <appointments>
        <appointment unitNumber="IN-CARD"
          jobCode="0010"
          appointmentType="APP"
          salary="50180"
          startDate="2010-01-01"
          jobTitle="Professor"
          preferedJobTitle="Professor"/>
      </appointments>
    </record>
    <!-- should produce an error for record 3 with principal name 'bobdobbs' because 
      BOGUS is not a valid unit number -->
    <record principalName="bobdobbs">
      <affiliations>
        <affiliation affiliationType="faculty"
          campus="MN"
          default="true"
          active="true">
          <employment
            employeeStatus="A"
            employeeType="P"
            baseSalaryAmount="50180"
            primaryDepartment="MATH"
            employeeId="092001234"
            primaryEmployment="true" />
        </affiliation>
      </affiliations>
      <addresses>
        <address addressTypeCode="HM"
          addressLine1="1234 E. Main St."
          addressLine2="Apt. 8C"
          city="Minneapolis"
          stateOrProvince="MN"
          postalCode="34567"
          country="US"
          default="true"
          active="true" />
      </addresses>
      <names>
        <name nameCode="PRM"
          prefix="Mr"
          firstName="Jonathon"
          middleName="R"
          lastName="Doe"
          default="true"
          active="true" />
      </names>
      <phones>
        <phone phoneType="WRK"
          phoneNumber="204-391-1101"
          country="US"
          default="true"
          active="true" />
        <phone phoneType="HM"
          phoneNumber="204-718-3221"
          country="US"
          active="true" />
      </phones>
      <emails>
        <email emailType="WRK"
          emailAddress="jdoe@university.edu"
          default="true"
          active="true" />
      </emails>
      <kcExtendedAttributes county="Maricopa"
        ageByFiscalYear="52"
        race="CAUCASIAN"
        educationLevel="PHD"
        degree="PhD"
        major="MATHEMATICS"
        handicapped="true"
        handicapType="TODO:handicapType"
        veteran="true"
        veteranType="A"
        visa="true"
        visaCode="TODO:visaCode"
        visaType="TODO:visaType"
        visaRenewalDate="2013-12-25"
        officeLocation="503 Carter Hall"
        secondaryOfficeLocation="88 Regan Hall"
        school="MATH"
        yearGraduated="1983"
        directoryDepartment="MATH"
        directoryTitle="Master of the Universe"
        primaryTitle="Leader of the Evil Horde"
        vacationAccrual="true"
        idProvided="John_Doe"
        idVerified="John_Doe_Verified"
        multiCampusPrincipalId="0002"
        multiCampusPrincipalName="jdoe2"
        onSabbatical="true"
        citizenshipType="1"
        salaryAnniversaryDate="2010-01-01"/>
      <degrees>
        <degree degree="PhD"
          degreeCode="DD"
          graduationYear="1983"
          fieldOfStudy="Mathematics"
          specialization="non-linear algebra"
          school="Texas A&amp;M University"
          schoolId="1234"
          schoolIdCode="UMN" />
      </degrees>
      <appointments>
        <appointment unitNumber="BOGUS"
          jobCode="0010"
          appointmentType="APP"
          salary="50180"
          startDate="2010-01-01"
          jobTitle="Professor"
          preferedJobTitle="Professor"/>
      </appointments>
    </record>
  </records>
</hrmanifest>
